[build]
  command = "npx prisma generate && npx prisma db push && node scripts/backfill-has-image.mjs && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
